apiVersion: operator.openshift.io/v1alpha1
kind: ImageContentSourcePolicy
metadata:
  name: release-0
spec:
  repositoryDigestMirrors:
  - mirrors:
    - image-registry.openshift-image-registry.svc:5000/openshift/release
    source: quay.io/openshift-release-dev/ocp-release
  - mirrors:
    - image-registry.openshift-image-registry.svc:5000/openshift/release
    source: quay.io/openshift-release-dev/ocp-v4.0-art-dev