apiVersion: v1
kind: Service
metadata:
  labels:
    apiserver: "true"
  name: api-server-lb
  namespace: openshift-apiserver
spec:
  selector:
    apiserver: "true"
  ports:
  - name: https
    port: 6443
    targetPort: 8443
    protocol: TCP
  type: LoadBalancer
