apiVersion: batch/v1
kind: Job
metadata:
  name: extract-cert
  namespace: openshift-config
spec:
  template:
    spec:
      containers:
      - name: label-nodes
        image: registry.openshift.local:3000/frqadmin/openshift/release:4.17.12-x86_64-cli
        command:
        - /bin/sh 
        - -c
        - |
          CLIENT_SECRET=$(openssl rand -base64 15) && \
          DB_PASSWORD=$(openssl rand -base64 15) && \
          oc create secret generic keycloak-db-secret-test --from-literal=username=keycloak --from-literal=password=$DB_PASSWORD -n keycloak && \
          oc create secret generic kc-client-secret --from-literal=clientSecret=$CLIENT_SECRET -n openshift-config && \
          oc create secret generic kc-client-secret --from-literal=clientSecret=$CLIENT_SECRET -n keycloak && \
          oc extract secret/router-ca -n openshift-ingress-operator && \
          oc create cm -n openshift-config keycloak-ca-configmap --from-file=ca.crt=tls.crt
      serviceAccount: extract-cert
      serviceAccountName: extract-cert
      restartPolicy: OnFailure
      terminationGracePeriodSeconds: 30

